version: '3.9'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest

    ports:
      - "8123:8123"
      - "9000:9000"

    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password

    ulimits:
      nofile:
        soft: 262144
        hard: 262144